/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Users } from '../models/users';
export interface Token {
  accessToken?: string;
  id?: number;
  loggedOut?: boolean;
  refreshToken?: string;
  user?: Users;
}
