/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Token } from '../models/token';
export interface Users {
  id?: number;
  password?: string;
  tokens?: Array<Token>;
  username?: string;
}
